### ISSUE TITLE
Issue with Vivint in Hoobs

### ISSUE THREAD

**Issue by 3aceskelsen** [hoobs-org/sidecars#10]
Anyone else having issues with the plugin? My accessories are showing in homekit, but not responding. When I try to get a new refresh token it looks like it's throwing errors, which I don't understand enough to know if that's the issue.
![Screen Shot 2021-11-28 at 9 29 55 AM 10 02 50 AM](https://user-images.githubusercontent.com/3276331/143778647-4f8944b0-3b32-400c-ae03-84149982e3b0.png)
<img width="749" alt="Screen Shot 2021-11-28 at 9 30 03 AM" src="https://user-images.githubusercontent.com/3276331/143778649-d8d41c3f-46c0-4509-8cc5-150294421f7a.png">

**Comment by 3aceskelsen** [comment]
Also this is the error in my log
<img width="1341" alt="Screen Shot 2021-11-28 at 10 17 42 AM" src="https://user-images.githubusercontent.com/3276331/143778725-739daaf1-b968-432a-8d42-6ef8411aedc8.png">
s

**Comment by askovi** [comment]
That looks like an internet connectivity issue. Reboot your router and the HOOBS box from the hub settings in the top right menu.

**Comment by 3aceskelsen** [comment]
@askovi Thanks, that seemed to work! I rebooted the raspberry pi earlier and that didn't work but rebooting the network did. Just for future reference what part indicated a network issue?

**Comment by askovi** [comment]
Code EAI_AGAIN

**Comment by 3aceskelsen** [comment]
Hey @askovi, you were the one to solve this issue last time so hoping you can help this time. I'm getting the same error that I did last year as posted above. I've rebooted my router and hoobs, but still no luck this time around. Appreciate any help, I've been working on this all evening, trying to find the solution.

**Comment by askovi** [comment]
See here: https://support.hoobs.org/topics/connectivity/plugin-site-unavailable

**Comment by 3aceskelsen** [comment]
@askovi Thanks so much! that was it! I definitely wouldn't have found that on my own!
